name: Singularity Build (manual)
on: 
  push:
    branches:
      - main

jobs:
  build-test-containers:
    runs-on: ubuntu-latest
    container:
      image: quay.io/singularity/singularity:v3.8.3
    strategy:
      fail-fast: false
      matrix:
        recipe: ["*.def"]

    name: Check ${{ matrix.recipe }}
    steps:

      - name: Check out code for the container build
        uses: actions/checkout@v2

      - name: Continue if Singularity Recipe Exists
        run: |
          if [[ -f "${{ matrix.recipe }}" ]]; then
            echo "keepgoing=true" >> $GITHUB_ENV
          fi          


      - name: Build Container
        if: ${{ env.keepgoing == 'true' }}
        env:
          recipe: ${{ matrix.recipe }}
        run: |
         ls 
         if [ -f "${{ matrix.recipe }}" ]; then
            CONTAINER_NAME=${{ matrix.recipe }}
            CONTAINER_NAME="${CONTAINER_NAME%.*}"
            echo $CONTAINER_NAME
            sudo -E singularity build $CONTAINER_NAME.sif ${{ matrix.recipe }}
            tag=$(echo "${recipe/Singularity\./}")
            if [ "$tag" == "Singularity" ]; then
                tag=latest
            else
                tag=dev
            fi
            # Build the container and name by tag
            echo "Tag is $tag."
            echo "tag=$tag" >> $GITHUB_ENV
         else
           echo "${{ matrix.recipe }} is not found."
           echo "Present working directory: $PWD"
           ls
         fi

      - name: Login and Deploy Container
        if: (github.event_name != 'pull_request')
        env:
          keepgoing: ${{ env.keepgoing }}
        run: |         
            if [[ "${keepgoing}" == "true" ]]; then
                echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
                singularity push container.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${tag}
            fi